### ISSUE TITLE
Calculations of PA1 and PA2 curvatures?

### ISSUE THREAD

**Issue by scith** [nicebread/RSA#2]
Hello, I was just wondering about these lines: https://github.com/nicebread/RSA/blob/3e51bc093c3a2b3ef85a1d9d5a32caf29fe5af8d/R/RSA.R#L328-L329

At the moment I do RSA using procedures from [Edwards and Parry (1993)](http://public.kenan-flagler.unc.edu/faculty/edwardsj/EdwardsParry1993.pdf). They compute the curvature of PA1 as `b3+b4*p11+b5*(p11^2)` of the curvature of PA2 as `b3+b4*p21+b5*(p21^2)`

I was thus wondering if you had a different rationale for computing them with the minus sign for `b3-b4` instead?

Thanks

**Comment by nicebread** [comment]
Thanks for reporting this bug (sorry for the delay; I missed the issue note). It's fixed in 0.9.11.
