### ISSUE TITLE
Difference in coefficients between polynomial regressions using OLS and RSA

### ISSUE THREAD

**Issue by rmoor** [nicebread/RSA#22]
Hi, I'm a rookie to RSA, which I found super powerful.

I tried to compare the results from lm (z~x*y + x^2+ y^2) and RSA(Z~X*Y, estimator = "ML, se ="standard"). It turns out that the coefficient estimates differed a lot. Is it because RSA uses ML? I'm wondering if there is a way to replicate the OLS results in RSA. 

Many thanks!

**Comment by nicebread** [comment]
Actually the coefficients should be (at least nearly) identical. We wrote a unit test that test exactly this equivalence (see https://github.com/nicebread/RSA/blob/master/tests/testthat/test-OLS-equivalence.R).

Can you provide a [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by nicebread** [comment]
Closed due to inactivity - re-open if necessary!

**Comment by YRHwang90** [comment]
I had a similar issue, and it turns out that the different coefficient estimates were due to the outlier.  The RSA() function removes outlier as a default setting. After including out.rm=FALSE, the coefficient estimates were identical.
