### ISSUE TITLE
Error lavaan WARNING

### ISSUE THREAD

**Issue by maipham123** [nicebread/RSA#26]
Hi, 

**I can not compute a new variable in this step**

> # Compute the RSA and save the result
> # into the new variable r1
> r1 <- RSA(postVA ~ ePow * iPow, data=motcon)

**The output message is** 

Error in nlminb(start = x.par, objective = auglag, gradient = fgrad, control = control,  : 
  NA/NaN gradient evaluation
In addition: Warning messages:
1: In lav_model_estimate(lavmodel = lavmodel, lavpartable = lavpartable,  :
  lavaan WARNING: the optimizer warns that a solution has NOT been found!
2: In lav_model_estimate(lavmodel = lavmodel, lavpartable = lavpartable,  :
  lavaan WARNING: the optimizer warns that a solution has NOT been found!

This happens to both the stable version and the development version of the package. I don't know if this is a bug or it's because of my R version 4.0.4 (2021-02-15). Thank you for your help!

Mai Pham

**Comment by nicebread** [comment]
This is a know problem, probably induced by an update of lavaan. We are working on this; in the meantime just leave out the SRSQD models, e.g.:

r1 <- RSA(postVA ~ ePow * iPow, data=motcon, models=c("full", "IA", "additive", "SQD", "RR", "SRR"))

**Comment by maipham123** [comment]
Thank you so much for the update.

Mai
