### ISSUE TITLE
How to conduct mediation or moderation model?

### ISSUE THREAD

**Issue by Tongzhao9417** [nicebread/RSA#28]
Hi Felix, it's an amazing package that I ever used! But I have a question that could this package conduct mediation or moderation model in polynomial regression and response surface analysis? Tell me if it possible.
Cheers for your bravo job!

**Comment by nicebread** [comment]
Thanks for your kind words! But no, it will not provide moderation or mediation in the foreseeable future.
I advise to run these models as custom lavaan models, and then use the plotRSA() function for plotting.

**Comment by Tongzhao9417** [comment]
> Thanks for your kind words! But no, it will not provide moderation or mediation in the foreseeable future. I advise to run these models as custom lavaan models, and then use the plotRSA() function for plotting.

Thanks for your reply, and that's a good idea to use lavaan model. 

Cheers!
