### ISSUE TITLE
Why the legend of z axis changed when I set zlim params?

### ISSUE THREAD

**Issue by Tongzhao9417** [nicebread/RSA#29]
Sorry for bother you again... I wonder to let the plot more beautiful, and I set "zlim" params as "c(1:4)". Then the legend of z axis change to "1-2" from "1-5" originally, and the color of plot also changed while I use zlim. My question is how to set the range of legend or how to remain the range of legend unchange when I modified the zlim params? Thx!!
attachment: 1:the plot of unchange zlim  2. zlim changed
1.
<img width="474" alt="iShot_2022-09-21_10 04 51" src="https://user-images.githubusercontent.com/42951960/191397821-d71ff897-c813-4515-bcee-56305548ae07.png">
2.
<img width="468" alt="image" src="https://user-images.githubusercontent.com/42951960/191397923-502d6d17-684d-44f5-bfa8-0ab069997591.png">

**Comment by nicebread** [comment]
Hi,

simply add:

pal.range="surface"


(But the the plot should by default choose a more sensible setting).
