### ISSUE TITLE
Add cubic models to RSA.R

### ISSUE THREAD

**Issue by nicebread** [nicebread/RSA#3]
- rename b6 to b9 (currently used for absdiff models) to w1, w2, w3
- use b6 to b9 for cubic coefficients
- Add a flag to the RSA output list whether a cubic model is present: cubic=TRUE/FALSE
- Define poly string in two ways: 2nd degree or 3rd degree
 - Use 2nd degree if no cubic models are in the model set
- Define a set of constraints as a string that set all cubic coefficients to zero; this is added to all 2nd degree models if a 3rd degree model is present

**Comment by sarahhumberg** [comment]
First two bullet points (renaming of coefficients) done: b5ed992

**Comment by nicebread** [comment]
Nice :-)

**Comment by sarahhumberg** [comment]
Remaining four bullet points (adaptions in RSA() function for the case that cubic models are in the model set) done: fa737db
